### ISSUE TITLE
New with 3.6 - Database is locked error with Python-based install

### ISSUE THREAD

**Issue by jl-678** [healthchecks/healthchecks#1072]
I upgraded yesterday from 3.4, which was completely solid for me. I never had any issues. Now I am seeing these new errors with 3.6 which are frustrating. As an aside, Iam experienced with installing and maintaining HC.

1. I am installing via python (no docker for me!)
2. I am using a sqlite DB (it is a home system with minimal volume and clients and so a real DB is too much)
3. HC is running in an Intel VM at Oracle Cloud

**The problem:**
Healthchecks works perfectly, then once every few hours, it fails with a 500 error. Below is the output from Python showing the 500 error. Note that 4 minutes later everything responds normally and returns with a 200. The problem happens periodically, and otherwise everything seems normal.

To reiterate the obvious, I never saw anything like this with 3.4.

```
[18/Oct/2024 08:50:01] "GET /ping/12f6f88c-ad08-4829-93a0-0af4501ccbae HTTP/1.1" 200 2
[18/Oct/2024 08:52:01] "GET /ping/5f4acb44-b76f-4169-9b7b-3e8ae7b6bdc0 HTTP/1.1" 200 2
[18/Oct/2024 08:52:02] "GET /ping/12f6f88c-ad08-4829-93a0-0af4501ccbae HTTP/1.1" 200 2
[18/Oct/2024 08:54:01] "GET /ping/5f4acb44-b76f-4169-9b7b-3e8ae7b6bdc0 HTTP/1.1" 200 2
[18/Oct/2024 08:54:08] "GET /ping/12f6f88c-ad08-4829-93a0-0af4501ccbae HTTP/1.1" 500 145
[18/Oct/2024 08:56:01] "GET /ping/12f6f88c-ad08-4829-93a0-0af4501ccbae HTTP/1.1" 200 2
[18/Oct/2024 08:56:02] "GET /ping/5f4acb44-b76f-4169-9b7b-3e8ae7b6bdc0 HTTP/1.1" 200 2
[18/Oct/2024 08:58:01] "GET /ping/5f4acb44-b76f-4169-9b7b-3e8ae7b6bdc0 HTTP/1.1" 200 2
[18/Oct/2024 08:58:02] "GET /ping/12f6f88c-ad08-4829-93a0-0af4501ccbae HTTP/1.1" 200 2
```
Django then emails me with lots of stuff. The subject is _"[Django] ERROR (EXTERNAL IP): Internal Server Error: /ping/12f6f88c-ad08-4829-93a0-0af4501ccbae"_. Here is the stack trace:

```
Internal Server Error: /ping/12f6f88c-ad08-4829-93a0-0af4501ccbae

OperationalError at /ping/12f6f88c-ad08-4829-93a0-0af4501ccbae
database is locked

Request Method: GET
Request URL: http://<myhostname>/ping/12f6f88c-ad08-4829-93a0-0af4501ccbae
Django Version: 5.1.1
Python Executable: /home/ubuntu/python/healthchecks/venv/bin/python
Python Version: 3.10.12
Python Path: ['/home/ubuntu/python/healthchecks/healthchecks-3.6', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages']
Server time: Fri, 18 Oct 2024 08:54:01 +0000
Installed Applications:
('hc.accounts',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'compressor',
 'hc.api',
 'hc.front',
 'hc.logs',
 'hc.payments')
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'hc.accounts.middleware.CustomHeaderMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'hc.accounts.middleware.TeamAccessMiddleware']


Traceback (most recent call last):
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)

The above exception (database is locked) was the direct cause of the following exception:
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/python/healthchecks/healthchecks-3.6/hc/api/views.py", line 211, in ping
    check.ping(remote_addr, scheme, method, ua, body, action, rid, exitstatus)
  File "/home/ubuntu/python/healthchecks/healthchecks-3.6/hc/api/models.py", line 487, in ping
    self.save()
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/python/healthchecks/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)

Exception Type: OperationalError at /ping/12f6f88c-ad08-4829-93a0-0af4501ccbae
Exception Value: database is locked
Raised during: hc.api.views.ping
Request information:
USER: AnonymousUser

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data
```

**Comment by cuu508** [comment]
Duplicate of #1057
