### ISSUE TITLE
Error in v3.8 Migrate: illegal instruction (sqlite db)

### ISSUE THREAD

**Issue by psyciknz** [healthchecks/healthchecks#1101]
I have healthchecks under watchtower (for good or bad).  Yesterday it updated to latest, which would be version 3.8.  And died.   In diagnosing, I found that when it's starting it's getting a illegal instruction running `./manage.py migrate` - I tried in a temporary container to run `./manage showmigrations` and it had the same error.  

I've reverted to 3.7 and have managed to get container back up.

Here is a log with the container starting

```
healthchecks  | [uWSGI] getting INI configuration from /opt/healthchecks/docker/uwsgi.ini
healthchecks  | [uwsgi-static] added check for static-collected/
healthchecks  | *** Starting uWSGI 2.0.28 (64bit) on [Wed Dec 11 08:44:13 2024] ***
healthchecks  | compiled with version: 12.2.0 on 09 December 2024 17:02:37
healthchecks  | os: Linux-6.8.12-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-2 (2024-09-05T10:03Z)
healthchecks  | nodename: d5a0a852ca8c
healthchecks  | machine: x86_64
healthchecks  | clock source: unix
healthchecks  | pcre jit disabled
healthchecks  | detected number of CPU cores: 4
healthchecks  | current working directory: /opt/healthchecks
healthchecks  | detected binary path: /usr/local/bin/uwsgi
healthchecks  | *** dumping internal routing table ***
healthchecks  | [rule: 0] subject: https://healthchecks.mydomain.com;https?:\/\/.+(\/.+) func: regexp action: setscriptname:$1
healthchecks  | [rule: 1] action: fixpathinfo:
healthchecks  | *** end of the internal routing table ***
healthchecks  | chdir() to /opt/healthchecks
healthchecks  | your memory page size is 4096 bytes
healthchecks  | detected max file descriptor number: 10000
healthchecks  | !!! no /etc/mime.types file found !!!
healthchecks  | lock engine: pthread robust mutexes
healthchecks  | thunder lock: enabled
healthchecks  | uwsgi socket 0 bound to TCP address :8000 fd 3
healthchecks  | Python version: 3.13.0 (main, Dec  3 2024, 02:26:48) [GCC 12.2.0]
healthchecks  | Python main interpreter initialized at 0x73e798eb9a60
healthchecks  | python threads support enabled
healthchecks  | your server socket listen backlog is limited to 100 connections
healthchecks  | your mercy for graceful operations on workers is 60 seconds
healthchecks  | setting request body buffering size to 16192 bytes
healthchecks  | mapped 588920 bytes (575 KB) for 4 cores
healthchecks  | *** Operational MODE: preforking ***
healthchecks  | running "exec:./manage.py migrate" (pre app)...
healthchecks  | Illegal instruction
healthchecks  | command "./manage.py migrate" exited with non-zero code: 132
healthchecks  | Wed Dec 11 08:44:15 2024 - FATAL hook failed, destroying instance
healthchecks  | SIGINT/SIGTERM received...killing workers...
healthchecks  | WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x73e798eb9a60 pid: 1 (default app)
healthchecks  | *** uWSGI is running in multiple interpreter mode ***
healthchecks  | spawned uWSGI master process (pid: 1)
healthchecks  | spawned uWSGI worker 1 (pid: 8, cores: 1)
healthchecks  | spawned uWSGI worker 2 (pid: 9, cores: 1)
healthchecks  | spawned uWSGI worker 3 (pid: 10, cores: 1)
healthchecks  | spawned uWSGI worker 4 (pid: 11, cores: 1)
healthchecks  | [uwsgi-daemons] spawning "./manage.py sendalerts --skip-checks" (uid: 999 gid: 999)
healthchecks  | [uwsgi-daemons] spawning "./manage.py sendreports --loop --skip-checks" (uid: 999 gid: 999)
healthchecks  | sendalerts is now running
healthchecks  | Admin Command Error: ./manage.py sendalerts --skip-checks
healthchecks  | Traceback (most recent call last):
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
healthchecks  |     return self.cursor.execute(sql, params)
healthchecks  |            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
healthchecks  |     return super().execute(query, params)
healthchecks  |            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
healthchecks  | sqlite3.OperationalError: table api_flip has no column named reason
healthchecks  |
healthchecks  | The above exception was the direct cause of the following exception:
healthchecks  |
healthchecks  | Traceback (most recent call last):
healthchecks  |   File "/opt/healthchecks/./manage.py", line 13, in <module>
healthchecks  |     execute_from_command_line(sys.argv)
healthchecks  |     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
healthchecks  |     utility.execute()
healthchecks  |     ~~~~~~~~~~~~~~~^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/__init__.py", line 436, in execute
healthchecks  |     self.fetch_command(subcommand).run_from_argv(self.argv)
healthchecks  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 413, in run_from_argv
healthchecks  |     self.execute(*args, **cmd_options)
healthchecks  |     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 459, in execute
healthchecks  |     output = self.handle(*args, **options)
healthchecks  |   File "/opt/healthchecks/hc/api/management/commands/sendalerts.py", line 202, in handle
healthchecks  |     while self.handle_going_down() and not self.shutdown:
healthchecks  |           ~~~~~~~~~~~~~~~~~~~~~~^^
healthchecks  |   File "/opt/healthchecks/hc/api/management/commands/sendalerts.py", line 176, in handle_going_down
healthchecks  |     flip.save()
healthchecks  |     ~~~~~~~~~^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 892, in save
healthchecks  |     self.save_base(
healthchecks  |     ~~~~~~~~~~~~~~^
healthchecks  |         using=using,
healthchecks  |         ^^^^^^^^^^^^
healthchecks  |     ...<2 lines>...
healthchecks  |         update_fields=update_fields,
healthchecks  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
healthchecks  |     )
healthchecks  |     ^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 998, in save_base
healthchecks  |     updated = self._save_table(
healthchecks  |         raw,
healthchecks  |     ...<4 lines>...
healthchecks  |         update_fields,
healthchecks  |     )
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 1161, in _save_table
healthchecks  |     results = self._do_insert(
healthchecks  |         cls._base_manager, using, fields, returning_fields, raw
healthchecks  |     )
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 1202, in _do_insert
healthchecks  |     return manager._insert(
healthchecks  |            ~~~~~~~~~~~~~~~^
healthchecks  |         [self],
healthchecks  |         ^^^^^^^
healthchecks  |     ...<3 lines>...
healthchecks  |         raw=raw,
healthchecks  |         ^^^^^^^^
healthchecks  |     )
healthchecks  |     ^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
healthchecks  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
healthchecks  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1847, in _insert
healthchecks  |     return query.get_compiler(using=using).execute_sql(returning_fields)
healthchecks  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1836, in execute_sql
healthchecks  |     cursor.execute(sql, params)
healthchecks  |     ~~~~~~~~~~~~~~^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
healthchecks  |     return super().execute(sql, params)
healthchecks  |            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
healthchecks  |     return self._execute_with_wrappers(
healthchecks  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
healthchecks  |         sql, params, many=False, executor=self._execute
healthchecks  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
healthchecks  |     )
healthchecks  |     ^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
healthchecks  |     return executor(sql, params, many, context)
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
healthchecks  |     with self.db.wrap_database_errors:
healthchecks  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
healthchecks  |     raise dj_exc_value.with_traceback(traceback) from exc_value
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
healthchecks  |     return self.cursor.execute(sql, params)
healthchecks  |            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
healthchecks  |     return super().execute(query, params)
healthchecks  |            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
healthchecks  | django.db.utils.OperationalError: table api_flip has no column named reason
healthchecks  |
healthchecks  | Traceback (most recent call last):
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
healthchecks  |     return self.cursor.execute(sql, params)
healthchecks  |            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
healthchecks  |     return super().execute(query, params)
healthchecks  |            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
healthchecks  | sqlite3.OperationalError: table api_flip has no column named reason
healthchecks  |
healthchecks  | The above exception was the direct cause of the following exception:
healthchecks  |
healthchecks  |
healthchecks  | Traceback (most recent call last):
healthchecks  |   File "/opt/healthchecks/./manage.py", line 17, in <module>
healthchecks  |     raise e
healthchecks  |   File "/opt/healthchecks/./manage.py", line 13, in <module>
healthchecks  |     execute_from_command_line(sys.argv)
healthchecks  |     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
healthchecks  |     utility.execute()
healthchecks  |     ~~~~~~~~~~~~~~~^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/__init__.py", line 436, in execute
healthchecks  |     self.fetch_command(subcommand).run_from_argv(self.argv)
healthchecks  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 413, in run_from_argv
healthchecks  |     self.execute(*args, **cmd_options)
healthchecks  |     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 459, in execute
healthchecks  |     output = self.handle(*args, **options)
healthchecks  |   File "/opt/healthchecks/hc/api/management/commands/sendalerts.py", line 202, in handle
healthchecks  |     while self.handle_going_down() and not self.shutdown:
healthchecks  |           ~~~~~~~~~~~~~~~~~~~~~~^^
healthchecks  |   File "/opt/healthchecks/hc/api/management/commands/sendalerts.py", line 176, in handle_going_down
healthchecks  |     flip.save()
healthchecks  |     ~~~~~~~~~^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 892, in save
healthchecks  |     self.save_base(
healthchecks  |     ~~~~~~~~~~~~~~^
healthchecks  |         using=using,
healthchecks  |         ^^^^^^^^^^^^
healthchecks  |     ...<2 lines>...
healthchecks  |         update_fields=update_fields,
healthchecks  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
healthchecks  |     )
healthchecks  |     ^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 998, in save_base
healthchecks  |     updated = self._save_table(
healthchecks  |         raw,
healthchecks  |     ...<4 lines>...
healthchecks  |         update_fields,
healthchecks  |     )
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 1161, in _save_table
healthchecks  |     results = self._do_insert(
healthchecks  |         cls._base_manager, using, fields, returning_fields, raw
healthchecks  |     )
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 1202, in _do_insert
healthchecks  |     return manager._insert(
healthchecks  |            ~~~~~~~~~~~~~~~^
healthchecks  |         [self],
healthchecks  |         ^^^^^^^
healthchecks  |     ...<3 lines>...
healthchecks  |         raw=raw,
healthchecks  |         ^^^^^^^^
healthchecks  |     )
healthchecks  |     ^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
healthchecks  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
healthchecks  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1847, in _insert
healthchecks  |     return query.get_compiler(using=using).execute_sql(returning_fields)
healthchecks  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1836, in execute_sql
healthchecks  |     cursor.execute(sql, params)
healthchecks  |     ~~~~~~~~~~~~~~^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
healthchecks  |     return super().execute(sql, params)
healthchecks  |            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
healthchecks  |     return self._execute_with_wrappers(
healthchecks  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
healthchecks  |         sql, params, many=False, executor=self._execute
healthchecks  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
healthchecks  |     )
healthchecks  |     ^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
healthchecks  |     return executor(sql, params, many, context)
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
healthchecks  |     with self.db.wrap_database_errors:
healthchecks  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
healthchecks  |     raise dj_exc_value.with_traceback(traceback) from exc_value
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
healthchecks  |     return self.cursor.execute(sql, params)
healthchecks  |            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
healthchecks  |   File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
healthchecks  |     return super().execute(query, params)
healthchecks  |            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
healthchecks  | django.db.utils.OperationalError: table api_flip has no column named reason
healthchecks  | sendreports is now running
healthchecks  | daemon "./manage.py sendalerts --skip-checks" (pid: 12) annihilated
```

Here is the compose file (abridged):
```
  healthchecks:
    image: healthchecks/healthchecks:latest
    container_name: healthchecks
    environment:
      - APPRISE_ENABLED=False
      - DB=sqlite
      - DB_CONN_MAX_AGE=0
      #- DB_HOST=
      - DB_NAME=/db/hc.sqlite
      #- DB_PASSWORD=
      #- DB_PORT=
      #- DB_SSLMODE=
      #- DB_TARGET_SESSION_ATTRS=
      #- DB_USER=
      - DEBUG=True
      - DEFAULT_FROM_EMAIL=${FASTMAILUSER}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - /hdd/docker-data/network_access/healthchecks/:/db
      - /hdd/docker-data/network_access/healthchecks/logo.png:/opt/healthchecks/static/logo.png
    ports:
      - 8000:8000
      - 2526:2525
    restart: unless-stopped
```

**Comment by psyciknz** [comment]
What hardware are you running on?
AMD cpu 


Are you using virtualization, like proxmox? If yes, what version?
Yes proxmox server v8, but health checks is running in docker on an lxc container 



Is watchtower this watchtower?
Containarr/watchtower 

And just to make sure, are you running the official docker image (https://hub.docker.com/r/healthchecks/healthchecks)?

Yes official.



I wonder if it's something the python 13 change?

**Comment by cuu508** [comment]
To fix this, I first need to reproduce it. Please let me know if I got your setup straight:

* You are running Proxmox v8 (v8.3?) on a bare metal server with AMD CPU
* Inside Proxmox system you run a LXC container based on the Debian 12 template
* Inside the container you have installed Docker
* Inside container, using docker, you are running the Healthchecks container from https://hub.docker.com/r/healthchecks/healthchecks

I'm not sure where watchtower comes into play. I have not used proxmox or watchtower before, so please excuse me if I've completely misunderstood.

**Comment by psyciknz** [comment]
Yes you have that correct.   Watchtower just checks for new versions and pulls a new copy.

I don't think it's relevant.

I have another proxmox machine.  Very similar stack.  So I can pull 3.8 version on that and see if I get the same error.

**Comment by cuu508** [comment]
The host system I'm using has Intel 9700K CPU.

I installed Proxmox 8.3.0 in a Virtualbox VM from ISO file. For the VM running Proxmox I used bridged network adapter. I set its "Promiscuous mode" setting to "Allow All".

I created Debian 12 Standard LXC container. When creating it, I unchecked "Unprivileged", and I unchecked "Firewall".

In container's Options > Features I enabled nesting.

Inside the container, I ran "apt update && apt upgrade" and installed Docker using [the get-docker.sh script](https://github.com/docker/docker-install). 

I then launched Healthchecks Docker container like so:

```
docker run \
  --name=healthchecks \
  -p 8000:8000 \
  --restart unless-stopped \
  -e ALLOWED_HOSTS=localhost \
  -e DB=sqlite \
  -e DB_NAME=/data/hc.sqlite \
  -e DEBUG=False \
  -e DEFAULT_FROM_EMAIL=fixme-email-address-here \
  -e EMAIL_HOST=fixme-smtp-host-here \
  -e EMAIL_HOST_PASSWORD=fixme-smtp-password-here \
  -e EMAIL_HOST_USER=fixme-smtp-username-here \
  -e EMAIL_PORT=587 \
  -e EMAIL_USE_TLS=True \
  -e SECRET_KEY=--- \
  -e SITE_ROOT=http://localhost:8000 \
  -v healthchecks-data:/data \
healthchecks/healthchecks:latest
```

Excerpt from output:

```
[uWSGI] getting INI configuration from /opt/healthchecks/docker/uwsgi.ini
[uwsgi-static] added check for static-collected/
*** Starting uWSGI 2.0.28 (64bit) on [Fri Dec 13 07:40:57 2024] ***
compiled with version: 12.2.0 on 09 December 2024 17:02:37
os: Linux-6.8.12-4-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-4 (2024-11-06T15:04Z)
nodename: 44fe72f6b69e
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /opt/healthchecks
detected binary path: /usr/local/bin/uwsgi
*** dumping internal routing table ***
[rule: 0] subject: http://localhost:8000;https?:\/\/.+(\/.+) func: regexp action: setscriptname:$1
[rule: 1] action: fixpathinfo:
*** end of the internal routing table ***
chdir() to /opt/healthchecks
your memory page size is 4096 bytes
detected max file descriptor number: 10000
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address :8000 fd 3
Python version: 3.13.0 (main, Dec  3 2024, 02:26:48) [GCC 12.2.0]
Python main interpreter initialized at 0x71c413582a60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 16192 bytes
mapped 588920 bytes (575 KB) for 4 cores
*** Operational MODE: preforking ***
running "exec:./manage.py migrate" (pre app)...
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, logs, payments, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying accounts.0001_initial... OK
  Applying accounts.0002_profile_ping_log_limit... OK
[...]
```

So, in my case, I didn't get the "Illegal instruction" error, and am still unable to reproduce the issue.

**Comment by cuu508** [comment]
I updated the Dockerfile to use python 3.13.1. The 3.13.1 [changelog](https://docs.python.org/3/whatsnew/changelog.html) mentions illegal operation, but the fix there is for a different architecture. Still, there's a tiny chance it also affects this issue. 

I pushed an image tagged "master" to docker hub. Could you try it out on your system and see what happens? Note, this is a temporary image, for testing only, I will remove it later.

**Comment by psyciknz** [comment]
Pulling that seemed to work.

`[uWSGI] getting INI configuration from /opt/healthchecks/docker/uwsgi.ini
[uwsgi-static] added check for static-collected/
*** Starting uWSGI 2.0.28 (64bit) on [Sat Dec 14 00:07:37 2024] ***
compiled with version: 12.2.0 on 13 December 2024 08:10:37
os: Linux-6.8.12-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-2 (2024-09-05T10:03Z)
nodename: 3c13c0b358d7
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /opt/healthchecks
detected binary path: /usr/local/bin/uwsgi
*** dumping internal routing table ***
[rule: 0] subject: https://healthchecks.internal.andc.nz;https?:\/\/.+(\/.+) func: regexp action: setscriptname:$1
[rule: 1] action: fixpathinfo:
*** end of the internal routing table ***
chdir() to /opt/healthchecks
your memory page size is 4096 bytes
detected max file descriptor number: 10000
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address :8000 fd 3
Python version: 3.13.0 (main, Dec  3 2024, 02:26:48) [GCC 12.2.0]
Python main interpreter initialized at 0x779acf206a60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 16192 bytes
mapped 588920 bytes (575 KB) for 4 cores
*** Operational MODE: preforking ***
running "exec:./manage.py migrate" (pre app)...
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, logs, payments, sessions
Running migrations:
  Applying accounts.0049_convert_email_lowercase... OK
  Applying api.0113_alter_channel_kind... OK
  Applying api.0114_flip_reason... OK
  Applying api.0115_flip_api_flip_owner_created... OK
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x779acf206a60 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 8, cores: 1)
spawned uWSGI worker 2 (pid: 9, cores: 1)
spawned uWSGI worker 3 (pid: 10, cores: 1)
spawned uWSGI worker 4 (pid: 11, cores: 1)
[uwsgi-daemons] spawning "./manage.py sendalerts --skip-checks" (uid: 999 gid: 999)
[uwsgi-daemons] spawning "./manage.py sendreports --loop --skip-checks" (uid: 999 gid: 999)
sendreports is now running
sendalerts is now running
`

**Comment by cuu508** [comment]
I've pushed Healthchecks 3.8.1 on Docker Hub. It uses Python 3.13.1 same as the experimental image.
