### ISSUE TITLE
error during ./manage.py migrate

### ISSUE THREAD

**Issue by jonathanparsy** [healthchecks/healthchecks#314]
Hi,
in the end of install process when i run ./manage.py migrate
i get this:
```
(hc-venv) check@healthcheck:~/webapps/healthchecks$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/check/webapps/hc-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/check/webapps/hc-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/check/webapps/hc-venv/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/check/webapps/hc-venv/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/check/webapps/hc-venv/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/check/webapps/healthchecks/hc/settings.py", line 39, in <module>
    for line in f.readlines():
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1970: ordinal not in range(128)
```
what can i do?

cc: @ilanmimoun

**Comment by SuperSandro2000** [comment]
Do you have a non ASCII char in your settings somewhere?

**Comment by cuu508** [comment]
There's a bit of code in settings.py that parses version from CHANGELOG.md, and it's throwing this exception.

CHANGELOG.md does indeed have a non-ASCII character in it: "–". But in my testing this works fine with Python 3.6 – 3.8.

@jonathanparsy are you by any chance trying to use Python 2.7?

**Comment by cuu508** [comment]
Ah, I can reproduce this if I set LC_ALL=C environment variable. Test snippet:

```
f = open("/tmp/test.txt", "wb")
f.write("foo – bar\n## v1.12".encode("utf-8"))
f.close()

VERSION = "???"
with open("/tmp/test.txt") as f:
    for line in f.readlines():
        if line.startswith("## v"):
            VERSION = line.split()[1]
            break

print("version:", VERSION)

```

**Comment by SuperSandro2000** [comment]
Python breaks with LC_ALL=C.
See https://github.com/docker-library/python/blob/0b1fb9529c79ea85b8c80ff3dd85a32a935b0346/3.8/buster/Dockerfile#L12

**Comment by cuu508** [comment]
OK, then that's the main issue. 

BTW I reproduced the problem with the full Healthchecks codebase too. Dockerfile:

```
FROM python:3.6

COPY requirements.txt /tmp
RUN pip install --no-cache-dir -r /tmp/requirements.txt
RUN pip install --no-cache-dir mock apprise

RUN groupadd -g 999 hc && useradd -r -u 999 --home /opt/healthchecks -g hc hc
WORKDIR /opt/healthchecks

COPY . .
RUN chown -R hc:hc /opt/healthchecks
USER hc

CMD [ "python3", "/opt/healthchecks/manage.py", "test"]


```

Running it like so works:

    docker build -t foo . && docker run -it foo

But this did not (before the fix):

    docker build -t foo . && docker run -e LC_ALL=C -it foo

**Comment by cuu508** [comment]
@SuperSandro2000  Not in the settings, but in CHANGELOG.md which gets read when loading settings. There's a "–" character in there.

**Comment by jonathanparsy** [comment]
> sys.getdefaultencoding()

````
>>> import sys
>>> sys.getdefaultencoding()
'ascii'
````

**Comment by jonathanparsy** [comment]
> Ah, I can reproduce this if I set LC_ALL=C environment variable.
> 
> I started python shell like so:
> 
> ```
> docker run --rm -it -e LC_ALL=C python:3.6
> ```
> 
> And ran this:
> 
> ```
> f = open("/tmp/test.txt", "wb")
> f.write(b'foo \xe2\x80\x93 bar\n## v1.12')
> f.close()
> 
> VERSION = "???"
> with open("/tmp/test.txt") as f:
>     for line in f.readlines():
>         if line.startswith("## v"):
>             VERSION = line.split()[1]
>             break
> 
> print("version:", VERSION)
> ```

indeed:
````
(hc-venv) check@healthcheck:~/webapps/healthchecks$ locale
LANG=C
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
````

**Comment by jonathanparsy** [comment]
So, i made change in locale, and i've quit the idea of a proxmox ubuntu container for a full ubuntu vm it works fine
thx for your help
