### ISSUE TITLE
sendalerts doesn't work with new failures

### ISSUE THREAD

**Issue by bobelev** [healthchecks/healthchecks#62]
Keep getting this stacktrace while testing notifications.
```
Sending alert, status=grace, code=11f7ef3e-bc25-4d85-8930-80090aab7418
Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/hc/api/management/commands/sendalerts.py", line 62, in handle
    if self.handle_many():
  File "/app/hc/api/management/commands/sendalerts.py", line 31, in handle_many
    future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/hc/api/management/commands/sendalerts.py", line 50, in handle_one
    errors = check.send_alert()
  File "/app/hc/api/models.py", line 72, in send_alert
    raise NotImplementedError("Unexpected status: %s" % self.status)
```

Notifications seem to work when `./manage.py sendalerts` is invoked manually after 'check failure'. But when I start `sendalerts` in background I always get this stacktrace.

**Comment by cuu508** [comment]
@bobelev can you please give a little more detail on the steps to reproduce this? If you have a test database, can you make a SQL dump and send it to me?

There was a race condition in sendalerts command (between selecting check and sending a notification, the status can go from "up" to "grace"), and I just fixed that. But I'm not sure it's the same issue you are seeing.
