### ISSUE TITLE
DB_NAME for sqlite different than /tmp/hc.sqlite

### ISSUE THREAD

**Issue by alyvusal** [healthchecks/healthchecks#623]
Hi, When I use different location for DB_NAME like `DB_NAME=/db/hc.sqlite`
Error says can not find location

```
healthchecks-hc-1  | sendreports is now running
healthchecks-hc-1  | Traceback (most recent call last):
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
healthchecks-hc-1  |     self.connect()
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
healthchecks-hc-1  |     return func(*args, **kwargs)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 225, in connect
healthchecks-hc-1  |     self.connection = self.get_new_connection(conn_params)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
healthchecks-hc-1  |     return func(*args, **kwargs)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 206, in get_new_connection
healthchecks-hc-1  |     conn = Database.connect(**conn_params)
healthchecks-hc-1  | sqlite3.OperationalError: unable to open database file
healthchecks-hc-1  | 
healthchecks-hc-1  | The above exception was the direct cause of the following exception:
healthchecks-hc-1  | 
healthchecks-hc-1  | Traceback (most recent call last):
healthchecks-hc-1  |   File "/opt/healthchecks/./manage.py", line 10, in <module>
healthchecks-hc-1  |     execute_from_command_line(sys.argv)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
healthchecks-hc-1  |     utility.execute()
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
healthchecks-hc-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
healthchecks-hc-1  |     self.execute(*args, **cmd_options)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
healthchecks-hc-1  |     output = self.handle(*args, **options)
healthchecks-hc-1  |   File "/opt/healthchecks/hc/api/management/commands/sendreports.py", line 105, in handle
healthchecks-hc-1  |     while not self.sigterm and self.handle_one_report():
healthchecks-hc-1  |   File "/opt/healthchecks/hc/api/management/commands/sendreports.py", line 39, in handle_one_report
healthchecks-hc-1  |     profile = q.first()
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 753, in first
healthchecks-hc-1  |     for obj in (self if self.ordered else self.order_by("pk"))[:1]:
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 320, in __iter__
healthchecks-hc-1  |     self._fetch_all()
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1507, in _fetch_all
healthchecks-hc-1  |     self._result_cache = list(self._iterable_class(self))
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 57, in __iter__
healthchecks-hc-1  |     results = compiler.execute_sql(
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in execute_sql
healthchecks-hc-1  |     cursor = self.connection.cursor()
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
healthchecks-hc-1  |     return func(*args, **kwargs)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 284, in cursor
healthchecks-hc-1  |     return self._cursor()
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 260, in _cursor
healthchecks-hc-1  |     self.ensure_connection()
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
healthchecks-hc-1  |     return func(*args, **kwargs)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 243, in ensure_connection
healthchecks-hc-1  |     with self.wrap_database_errors:
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
healthchecks-hc-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
healthchecks-hc-1  |     self.connect()
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
healthchecks-hc-1  |     return func(*args, **kwargs)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 225, in connect
healthchecks-hc-1  |     self.connection = self.get_new_connection(conn_params)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
healthchecks-hc-1  |     return func(*args, **kwargs)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 206, in get_new_connection
healthchecks-hc-1  |     conn = Database.connect(**conn_params)
healthchecks-hc-1  | django.db.utils.OperationalError: unable to open database file
healthchecks-hc-1  | sendalerts is now running
healthchecks-hc-1  | Traceback (most recent call last):
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
healthchecks-hc-1  |     self.connect()
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
healthchecks-hc-1  |     return func(*args, **kwargs)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 225, in connect
healthchecks-hc-1  |     self.connection = self.get_new_connection(conn_params)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
healthchecks-hc-1  |     return func(*args, **kwargs)
healthchecks-hc-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 206, in get_new_connection
healthchecks-hc-1  |     conn = Database.connect(**conn_params)
healthchecks-hc-1  | sqlite3.OperationalError: unable to open database file
```

**Comment by cuu508** [comment]
Does the directory `/db/` exist? Do you have write permission on it?

**Comment by alyvusal** [comment]
Hi, I did not read about it on docs and docker hub. Now adding 999:999 solved issue. Thanks
