### ISSUE TITLE
increasing PING_BODY_LIMIT=100000 breaks all ping 500 Server error

### ISSUE THREAD

**Issue by pinkworld123** [healthchecks/healthchecks#727]
Hello,

I tried to increase the PING_BODY_LIMIT from 10KB to 100KB
PING_BODY_LIMIT=100000 # 100KB
also tried with None 
PING_BODY_LIMIT=None

which broke all ping and causes 500 Server Error when Ping URL is called.

Please let me know how to fix this issue. Thank you for help.

debug error 

```
Environment:


Request Method: GET
Request URL: https://healthchecks.xxx.com/ping/61cacb0f-126f-48de-a071-7f0ac0abcb53

Django Version: 4.1.2
Python Version: 3.10.5
Installed Applications:
('hc.accounts',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'compressor',
 'hc.api',
 'hc.front',
 'hc.payments')
Installed Middleware:
('django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'hc.accounts.middleware.CustomHeaderMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'hc.accounts.middleware.TeamAccessMiddleware')



Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/healthchecks/./hc/api/views.py", line 53, in ping
    body = request.body[: settings.PING_BODY_LIMIT]

Exception Type: TypeError at /ping/61cacb0f-126f-48de-a071-7f0ac0abcb53
Exception Value: slice indices must be integers or None or have an __index__ method

```

**Comment by pinkworld123** [comment]
I found the issue its a local_settings.py needs to be properly set as 
https://github.com/linuxserver/docker-healthchecks/issues/98. 

so if possible please allow PING_BODY_LIMIT='100000' as a string. thanks

**Comment by cuu508** [comment]
Disagree, the proper solution is to fix https://github.com/linuxserver/docker-healthchecks/issues/98

**Comment by BlackScreen** [comment]
I recently stumbled upon this issue. "None" seems to still not work and fall back to the default value. Can you fix this somehow, please? :)

**Comment by BlackScreen** [comment]
> @BlackScreen what Docker image are you using?

`image: healthchecks/healthchecks`

**Comment by cuu508** [comment]
@BlackScreen can you share steps to reproduce?

I tested the following: started a container like so:

```
docker run \
  --name=healthchecks \
  -p 8000:8000 \
  --restart unless-stopped \
  -e ALLOWED_HOSTS=localhost \
  -e DB=sqlite \
  -e DB_NAME=/data/hc.sqlite \
  -e DEBUG=False \
  -e DEFAULT_FROM_EMAIL=fixme-email-address-here \
  -e EMAIL_HOST=fixme-smtp-host-here \
  -e EMAIL_HOST_PASSWORD=fixme-smtp-password-here \
  -e EMAIL_HOST_USER=fixme-smtp-username-here \
  -e EMAIL_PORT=587 \
  -e EMAIL_USE_TLS=True \
  -e SECRET_KEY=--- \
  -e SITE_ROOT=http://localhost:8000 \
  -e PING_BODY_LIMIT=None \
  -v healthchecks-data:/data \
healthchecks/healthchecks:latest
```

Then opened a shell to it:

```
docker exec -it <container-id-here> bash
```

From inside the shell:

```
hc@cc24faa0258b:/opt/healthchecks$ python ./manage.py shell
Python 3.11.4 (main, Jun 14 2023, 18:25:14) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.conf import settings
>>> settings.PING_BODY_LIMIT is None
True
```

**Comment by BlackScreen** [comment]
> @BlackScreen can you share steps to reproduce?

I tested what you did and I also get "True". But: the body still is limited to 10000 bytes.

I am using docker compose. Here is my docker compose:

```
version: '3.3'

services:
  healthchecks-app:
    image: healthchecks/healthchecks
    container_name: healthchecks-app
    restart: always
    security_opt:
      - no-new-privileges:true
    command: bash -c 'while !</dev/tcp/healthchecks-db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
    environment:
      - ADMINS=user@mydomain.com
      - ALLOWED_HOSTS=health.mydomain.com
      - DB=postgres
      - DB_HOST=healthchecks-db
      - DB_PORT=5432
      - DB_NAME=healthchecks-database
      - DB_USER=healthchecks-database-user
      - DB_PASSWORD=healthchecks-database-pw
      - DEBUG=False
      - DEFAULT_FROM_EMAIL=service@mydomain.com
      - EMAIL_HOST=smtp.mydomain.com
      - EMAIL_HOST_USER=user@mydomain.com
      - EMAIL_HOST_PASSWORD=my-super-secret-mail-pw
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_USE_VERIFICATION=True
      - MATTERMOST_ENABLED=False
      - MSTEAMS_ENABLED=False
      - OPSGENIE_ENABLED=False
      - PAGERTREE_ENABLED=False
      - PD_ENABLED=False
      - PING_BODY_LIMIT=None
      - PROMETHEUS_ENABLED=False
      - REGISTRATION_OPEN=False
      - ROCKETCHAT_ENABLED=False
      - SECRET_KEY=my-super-secret-key
      - SITE_NAME=Healthchecks @ Home
      - SITE_ROOT=https://health.mydomain.com
      - SLACK_ENABLED=False
      - SPIKE_ENABLED=False
      - USE_PAYMENTS=False
      - VICTOROPS_ENABLED=False
      - WEBHOOKS_ENABLED=False
      - ZULIP_ENABLED=False
      - TZ=Europe/Berlin
    depends_on:
      - healthchecks-db

  healthchecks-db:
    image: postgres:15
    container_name: healthchecks-db
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_DB=healthchecks-database
      - POSTGRES_USER=healthchecks-database-user
      - POSTGRES_PASSWORD=healthchecks-database-pw
      - TZ=Europe/Berlin
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
```

**Comment by cuu508** [comment]
@BlackScreen are you perhaps using runitor, and it is doing the truncating, not Healthchecks?

And, second question, what version number shows up in the footer of Healthchecks web UI?

**Comment by BlackScreen** [comment]
> @BlackScreen are you perhaps using runitor, and it is doing the truncating, not Healthchecks?

Oh, dammit. You are right. I guess that could be the problem. I will look into that. Sorry for the confusion. :(
