### ISSUE TITLE
SMTP Authentication error if password has special characters

### ISSUE THREAD

**Issue by adocampo** [healthchecks/healthchecks#747]
Title says everything. I've tried with an email account we in every service we have in the company, but this account has a very complex password like this `>9Abt~:Wk$n:p:H3+Kkm.MDp"S4sUs?E`.
With the same settings, I've tried with my own email account, which has a simpler password without any special character, and it works, so the issue is in the password itself.

I've tried to put the password in simple quotes (as the password has double quotes in it) and also escaping the double quotes in it (my bet that was the culprit), and any combination of single/double quotes and escaping character (\) but I'm always receiving the same error.
```
healthchecks  | Exception in thread Thread-1:
healthchecks  | Traceback (most recent call last):
healthchecks  |   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
healthchecks  |     self.run()
healthchecks  |   File "/app/healthchecks/./hc/lib/emails.py", line 24, in run
healthchecks  |     self.message.send()
healthchecks  |   File "/usr/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
healthchecks  |     return self.get_connection(fail_silently).send_messages([self])
healthchecks  |   File "/usr/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 124, in send_messages
healthchecks  |     new_conn_created = self.open()
healthchecks  |   File "/usr/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 91, in open
healthchecks  |     self.connection.login(self.username, self.password)
healthchecks  |   File "/usr/lib/python3.10/smtplib.py", line 750, in login
healthchecks  |     raise last_exception
healthchecks  |   File "/usr/lib/python3.10/smtplib.py", line 739, in login
healthchecks  |     (code, resp) = self.auth(
healthchecks  |   File "/usr/lib/python3.10/smtplib.py", line 662, in auth
healthchecks  |     raise SMTPAuthenticationError(code, resp)
healthchecks  | smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials k14-20020adfb34e000000b00241f803c08asm35430wrd.98 - gsmtp')

```

Any clue?

**Comment by adocampo** [comment]
weird, the first thing i've tried was quote the password in single quotes (as I do on most services), but it didn't work when sending emails with the former error...
perhaps is because I'm using linuxserver container and it doesn't use the `.env` file, but a `local_settings.py`?

**Comment by cuu508** [comment]
I started a linuxserver image like so:

```
docker run -d \
  --name=healthchecks-xyz \
  -e PUID=1000 \
  -e PGID=1000 \
  -e SITE_ROOT= \
  -e SITE_NAME= \
  -e DEFAULT_FROM_EMAIL= \
  -e EMAIL_HOST= \
  -e EMAIL_PORT=587 \
  -e EMAIL_HOST_USER= \
  -e EMAIL_HOST_PASSWORD='>9Abt~:Wk$n:p:H3+Kkm.MDp"S4sUs?E' \
  -e EMAIL_USE_TLS= \
  -e SUPERUSER_EMAIL= \
  -e SUPERUSER_PASSWORD= \
  -e REGENERATE_SETTINGS= `#optional` \
  -e SITE_LOGO_URL= `#optional` \
  -e ALLOWED_HOSTS= `#optional` \
  -e SECRET_KEY= `#optional` \
  -e APPRISE_ENABLED= `#optional` \
  -e DEBUG= `#optional` \
  -p 8000:8000 \
  -v /path/to/data:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/healthchecks:latest
```

The email password looks good:

```
docker exec -it e1ca2dd266eb python3 /app/healthchecks/manage.py shell
Python 3.10.5 (main, Jul 25 2022, 15:52:08) [GCC 11.2.1 20220219] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.conf import settings
>>> settings.EMAIL_HOST_PASSWORD
'>9Abt~:Wk$n:p:H3+Kkm.MDp"S4sUs?E'
```

Can you check with `manage.py shell` in a running container the value of `django.conf.settings.EMAIL_HOST_PASSWORD`?

**Comment by cuu508** [comment]
No reply, closing.
