### ISSUE TITLE
Docker container: smtpd can't start as non-root user

### ISSUE THREAD

**Issue by 31239899** [healthchecks/healthchecks#791]
The current container image fails to start `smtpd` because the `hc` user doesn't have permission to bind port 25. Seems like either nobody is using incoming emails (because they haven't noticed it failing) or people are running the container using `--user root`.

I propose adding an environment variable to allow the `smtpd` process to listen on a user-specified port. Listening on unprivileged ports (>1024) is safer than running containers as root. Leaving the default value as 25 would avoid affecting existing installations.

Alternatively (or in addition), there could be an environment variable to turn off `smtpd` listening altogether for those who don't need it. Reduces the attack surface and resource usage.

Reproducers below. I'm running podman on Fedora 37, but the outcome should be the same running Docker.

Command: `podman run --name healthchecks --rm -d -p 127.0.0.1:8000:8000 -e DB_NAME=/tmp/hc.sqlite docker.io/healthchecks/healthchecks:latest`
Logs:
```
[uWSGI] getting INI configuration from /opt/healthchecks/docker/uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Sun Feb  5 13:11:23 2023] ***
compiled with version: 10.2.1 20210110 on 26 January 2023 07:27:23
os: Linux-6.1.9-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb  2 00:21:48 UTC 2023
nodename: f34aa321637b
machine: x86_64
clock source: unix
detected number of CPU cores: 12
current working directory: /opt/healthchecks
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/healthchecks
your processes number limit is 4194304
your memory page size is 4096 bytes
detected max file descriptor number: 10000
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address :8000 fd 3
Python version: 3.10.9 (main, Jan 23 2023, 22:43:18) [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x556d1d4bdee0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 405560 bytes (396 KB) for 4 cores
*** Operational MODE: preforking ***
running "exec:./manage.py migrate" (pre app)...
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions
Running migrations:

<snip>

WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x556d1d4bdee0 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 4, cores: 1)
spawned uWSGI worker 2 (pid: 5, cores: 1)
spawned uWSGI worker 3 (pid: 6, cores: 1)
spawned uWSGI worker 4 (pid: 7, cores: 1)
[uwsgi-daemons] spawning "./manage.py sendalerts" (uid: 999 gid: 999)
[uwsgi-daemons] spawning "./manage.py sendreports --loop" (uid: 999 gid: 999)
[uwsgi-daemons] spawning "./manage.py smtpd" (uid: 999 gid: 999)
sendalerts is now running
sendreports is now running
Admin Command Error: ./manage.py smtpd
Traceback (most recent call last):
  File "/opt/healthchecks/./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/healthchecks/hc/api/management/commands/smtpd.py", line 105, in handle
    _ = Listener((host, port), self.stdout)
  File "/opt/healthchecks/hc/api/management/commands/smtpd.py", line 82, in __init__
    super(Listener, self).__init__(localaddr, None, decode_data=False)
  File "/usr/local/lib/python3.10/smtpd.py", line 662, in __init__
    self.bind(localaddr)
  File "/usr/local/lib/python3.10/asyncore.py", line 333, in bind
    return self.socket.bind(addr)
PermissionError: [Errno 13] Permission denied
...
```

Command: `podman run --name healthchecks --rm -d -p 127.0.0.1:8000:8000 -e DB_NAME=/tmp/hc.sqlite --user root docker.io/healthchecks/healthchecks:latest`
Logs:
```
[uWSGI] getting INI configuration from /opt/healthchecks/docker/uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Sun Feb  5 13:12:33 2023] ***
compiled with version: 10.2.1 20210110 on 26 January 2023 07:27:23
os: Linux-6.1.9-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb  2 00:21:48 UTC 2023
nodename: 038690cf1230
machine: x86_64
clock source: unix
detected number of CPU cores: 12
current working directory: /opt/healthchecks
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /opt/healthchecks
your processes number limit is 4194304
your memory page size is 4096 bytes
detected max file descriptor number: 10000
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address :8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.9 (main, Jan 23 2023, 22:43:18) [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x55ed96a46ee0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 405560 bytes (396 KB) for 4 cores
*** Operational MODE: preforking ***
running "exec:./manage.py migrate" (pre app)...
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions
Running migrations:

<snip>

WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55ed96a46ee0 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 4, cores: 1)
spawned uWSGI worker 2 (pid: 5, cores: 1)
spawned uWSGI worker 3 (pid: 6, cores: 1)
spawned uWSGI worker 4 (pid: 7, cores: 1)
[uwsgi-daemons] spawning "./manage.py sendalerts" (uid: 0 gid: 0)
[uwsgi-daemons] spawning "./manage.py sendreports --loop" (uid: 0 gid: 0)
[uwsgi-daemons] spawning "./manage.py smtpd" (uid: 0 gid: 0)
sendreports is now running
sendalerts is now running
Starting SMTP listener on 0.0.0.0:25 ...
```

**Comment by cuu508** [comment]
Thanks for the suggestion, @31239899 !

I've updated uwsgi.ini to use the port specified in `SMTPD_PORT` environment variable, and skip `./manage.py smtpd` altogether if `SMTPD_PORT` is empty.

This seems to work now:

    podman run --name healthchecks --rm -p 127.0.0.1:8000:8000 -e DB_NAME=/tmp/hc.sqlite -e SMTPD_PORT=2525 localhost/experiment:latest

I'll update images on hub.docker.com on the next release, in a month or so. In the meantime you can build an image yourself. For testing, I built an image with podman using the following steps:

* downloaded healthchecks source from Github as a zip archive, extracted it
* copied the `docker/Dockerfile` to the project's root directory  (one level up)
* `podman build -f Dockerfile -t=experiment`

**Comment by 31239899** [comment]
Confirmed that it is working as expected with a local build. Thanks for the quick resolution @cuu508!

**Comment by alexanderadam** [comment]
Is there any ETA when this will be released in the Docker images?

**Comment by cuu508** [comment]
@alexanderadam v2.7 is now out!

**Comment by keithnet** [comment]
Can you add something to the documentation about this (https://healthchecks.io/docs/self_hosted_configuration/)? I didn't have SMTPD_PORT in my docker configuration. I've used every version, but it wasn't until 3.0 where SMTPD just stopped working for me. Luckily after a bunch of digging, I was able to determine I needed to add SMTPD_PORT to my configuration. There is nothing in the healthchecks.io docs about this configuration option.

**Comment by cuu508** [comment]
@keithnet thanks for the suggestion!

I updated docs at: https://healthchecks.io/docs/self_hosted_docker/

And here: https://github.com/healthchecks/healthchecks/tree/master/docker

I have not included `SMTPD_PORT` in the [Server Configuration](https://canary.healthchecks.io/docs/self_hosted_configuration/) page because this environment variable is not part of the Django app, it is specific to the [uWSGI configuration](https://github.com/healthchecks/healthchecks/blob/master/docker/uwsgi.ini) used in the official Docker image. For users using 3rd-party docker images, and for users not using Docker at all the `SMTPD_PORT` env var would have no effect.
