### ISSUE TITLE
SMTP session exception

### ISSUE THREAD

**Issue by techsolo12** [healthchecks/healthchecks#847]
Hello together,

unfortunately, the update to version 2.9.2 works not for me. Some hours after this update, i got a error message with smtp session exception. With version 2.8.1 i don't get any error messages.

The error log says that the db isn't reachable, but other application that use the same db still work as aspected.
When i change back to 2.8.1 everything works as normal.

Here is my config:
```services:
  healthchecks:
#    image: healthchecks/healthchecks:v2.8.1
    image: healthchecks/healthchecks:latest
    container_name: healthchecks
    user: "1001:1001"
    restart: always
    environment:
      ADMINS: admin@domain.tld
      # Used for running as non prod
      DEBUG: "False"
      # Disable http request logging
      UWSGI_DISABLE_LOGGING: "1"
      # Database settings
      DB: mysql
      DB_HOST: mariadb
      DB_NAME: healthchecks
      DB_USER: healthchecks
      DB_PASSWORD: "xxxxxxxx"
      # Email settings
      EMAIL_HOST: smtp.domain.tld
      EMAIL_PORT: 587
      EMAIL_HOST_USER: admin@domain.tld
      EMAIL_HOST_PASSWORD: "xxxxxxxx"
      EMAIL_USE_TLS: "True"
      DEFAULT_FROM_EMAIL: healthchecks@domain.tld
      # Force email verifications
      EMAIL_USE_VERIFICATION: "True"
      # Set to FQDN for container
      ALLOWED_HOSTS: hc.domain.tld
      # Ping body size (email attached max. log files size)
      PING_BODY_LIMIT: 5000000
      # Domain for ping email generation
      PING_EMAIL_DOMAIN: hc.domain.tld
      PUSHOVER_API_TOKEN: xxxxxxxxxxxx
      PUSHOVER_SUBSCRIPTION_URL: https://pushover.net/subscribe/xxxxxxx
      # Open registration for everyone
      REGISTRATION_OPEN: "False"
      # WebUI settings
      SITE_LOGO_URL: https://www.domain.tld
      SITE_NAME: Healthchecks
      SITE_ROOT: https://hc.domain.tld
      # Random creted secret key
      SECRET_KEY: "xxxxxxx"
      SMTPD_PORT: 2525
    ports:
    #  - "8000:8000"
      - "2525:2525"
    networks:
      - npm
      - sql
networks:
  npm:
    name: npm
    external: true
  sql:
    name: sql
    external: true
```

And this is the error log:

```[uWSGI] getting INI configuration from /opt/healthchecks/docker/uwsgi.ini
[uwsgi-static] added check for static-collected/
*** Starting uWSGI 2.0.21 (64bit) on [Thu Jun 15 09:03:56 2023] ***
compiled with version: 10.2.1 20210110 on 05 June 2023 20:42:11
os: Linux-5.15.0-1030-oracle #36-Ubuntu SMP Wed Feb 15 05:57:14 UTC 2023
nodename: df60ccb22ff9
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/healthchecks
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/healthchecks
your memory page size is 4096 bytes
detected max file descriptor number: 10000
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address :8000 fd 3
Python version: 3.11.3 (main, May 23 2023, 08:54:51) [GCC 10.2.1 20210110]
Python main interpreter initialized at 0xffffbd699900
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 16192 bytes
mapped 445560 bytes (435 KB) for 4 cores
*** Operational MODE: preforking ***
running "exec:./manage.py migrate" (pre app)...
System check identified some issues:

WARNINGS:
api.Check: (models.W037) MariaDB does not support indexes with conditions.
	HINT: Conditions will be ignored. Silence this warning if you don't care about it.
api.Flip: (models.W037) MariaDB does not support indexes with conditions.
	HINT: Conditions will be ignored. Silence this warning if you don't care about it.
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions
Running migrations:
  No migrations to apply.
  Your models in app(s): 'api' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xffffbd699900 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 9, cores: 1)
spawned uWSGI worker 2 (pid: 10, cores: 1)
spawned uWSGI worker 3 (pid: 11, cores: 1)
spawned uWSGI worker 4 (pid: 12, cores: 1)
[uwsgi-daemons] spawning "./manage.py sendalerts" (uid: 1001 gid: 1001)
[uwsgi-daemons] spawning "./manage.py smtpd --port 2525" (uid: 1001 gid: 1001)
[uwsgi-daemons] spawning "./manage.py sendreports --loop" (uid: 1001 gid: 1001)
sendalerts is now running
sendreports is now running
Starting SMTP listener on 0.0.0.0:2525 ...
Not an UUID: erorshimiciaw5
('xxx.xxx.xxx.xxx', 65190) unrecognised: GET
('xxx.xxx.xxx.xxx', 65190) unrecognised: HOST:
('xxx.xxx.xxx.xxx', 65190) unrecognised: USER-AGENT:
Not an UUID: erorshimiciaw5
Not an UUID: josewhiltawsky
Not an UUID: josewhiltawsky
('xxx.xxx.xxx.xxx', 58480) unrecognised: GET
('xxx.xxx.xxx.xxx', 58480) unrecognised: HOST:
('xxx.xxx.xxx.xxx', 58480) unrecognised: USER-AGENT:
('xxx.xxx.xxx.xxx', 55272) unrecognised: MGLNDD_130.61.79.228_2525
Processed ping for 91fa4cdd-a854-4813-8189-9bf353a1877c
Processed ping for 19e998bf-961b-49bf-a3cc-5732869d2e7d
Processed ping for f8290de5-b561-456e-97a7-9304bc1871f4
Processed ping for 547e6ac3-8e9d-4d3a-a57a-f02bcf965506
('xxx.xxx.xxx.xxx', 45280) unrecognised: ��8��'45.79.181.179', 45280) unrecognised: �
('xxx.xxx.xxx.xxx', 62002) unrecognised: GET
('xxx.xxx.xxx.xxx', 62002) unrecognised: HOST:
('xxx.xxx.xxx.xxx', 62002) unrecognised: USER-AGENT:
Processed ping for bb7136bb-24a1-4a99-832a-55c3a032b3c6
Processed ping for ce0f9218-bebe-4a7e-9979-85b27840f997
Processed ping for 1aac8e46-d37b-4719-9814-cb8137618f87
Processed ping for 3f63731e-e458-479f-b14c-e2a2c89b5cc7
Processed ping for 35110aac-aebc-4fc6-871c-c47cb84d4356
('xxx.xxx.xxx.xxx', 59603) unrecognised: �
Sending alert, status=down, code=180f4857-80b4-4dd6-b79e-a04cfd4c4166
 * OK     0.3s po         9145f266-aa64-4e72-9da6-22f568bb5430 
Sending took 0.3s, code=180f4857-80b4-4dd6-b79e-a04cfd4c4166
Sending alert, status=down, code=63a34eeb-878d-4cd4-84d1-71c5dedf2ce5
 * OK     0.7s po         9145f266-aa64-4e72-9da6-22f568bb5430 
Sending took 0.7s, code=63a34eeb-878d-4cd4-84d1-71c5dedf2ce5
('xxx.xxx.xxx.xxx', 5893) SMTP session exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 741, in _handle_client
    await method(arg)
  File "/usr/local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 1460, in smtp_DATA
    status = await self._call_handler_hook('DATA')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 473, in _call_handler_hook
    status = await hook(self, self.session, self.envelope, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/healthchecks/hc/api/management/commands/smtpd.py", line 94, in handle_DATA
    result = await self.process_message(remote_addr, mailfrom, mailto, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/healthchecks/hc/api/management/commands/smtpd.py", line 56, in _process_message
    check = Check.objects.get(code=code)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
('88.65.237.58', 6571) SMTP session exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 741, in _handle_client
    await method(arg)
  File "/usr/local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 1460, in smtp_DATA
    status = await self._call_handler_hook('DATA')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 473, in _call_handler_hook
    status = await hook(self, self.session, self.envelope, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/healthchecks/hc/api/management/commands/smtpd.py", line 94, in handle_DATA
    result = await self.process_message(remote_addr, mailfrom, mailto, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/healthchecks/hc/api/management/commands/smtpd.py", line 56, in _process_message
    check = Check.objects.get(code=code)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
('130.61.79.228', 54626) SMTP session exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (2006, 'MySQL server has gone away')```

Thanks for your time!

**Comment by cuu508** [comment]
I pushed a change that hopefully fixes this: https://github.com/healthchecks/healthchecks/commit/39dc7ecad0a68355509361a3ec1d61670e5800ca

@techsolo12 would you be able to test the master version, and see if you still get DB connection timeouts?

**Comment by cuu508** [comment]
To make testing easier, I built an image from code in the current master, tagged "master". I think this should work:

```
image: healthchecks/healthchecks:master
```

(I don't plan to rebuild the master image on every commit, and may remove this tag later. Use it for testing only)

**Comment by techsolo12** [comment]
I think this should be no problem. I have pulled the new image and will report in one or two days! :) Hopefully, everything work as aspected. Thank you for your time!

**Comment by techsolo12** [comment]
@cuu508 After 5 days of testing, i can say that everything works now as expected. No connection timeout or interrupts anymore! Thank you for your help! 
Do you release a new image version, or will the fix version stay online until you release a new version?

**Comment by cuu508** [comment]
Awesome, thanks for testing! I will release a new version.
