### ISSUE TITLE
ZoneInfoNotFoundError at `/checks/<guid>/details/`

### ISSUE THREAD

**Issue by abobija** [healthchecks/healthchecks#850]
I'm getting Server Error 500 when try to open the details of the check.
Not sure if is this something regarding the Healthchecks code or something regarding my environment?
I'm running Healthchecks inside of the docker container using `linuxserver/healthchecks:latest` image.

Please let me know if you need more information.

<details>
<summary>👉 Here is the error Traceback (click to expand)</summary>

```
Environment:

Request Method: GET
Request URL: https://<url>/checks/<guid>/details/

Django Version: 4.2.2
Python Version: 3.11.4
Installed Applications:
('hc.accounts',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'compressor',
 'hc.api',
 'hc.front',
 'hc.payments')
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'hc.accounts.middleware.CustomHeaderMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'hc.accounts.middleware.TeamAccessMiddleware']

Traceback (most recent call last):
  File "/usr/lib/python3.11/zoneinfo/_common.py", line 12, in load_tzdata
    return resources.files(package_name).joinpath(resource_name).open("rb")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/resources/_common.py", line 22, in files
    return from_package(get_package(package))
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/resources/_common.py", line 53, in get_package
    resolved = resolve(package)
               ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/resources/_common.py", line 44, in resolve
    return cand if isinstance(cand, types.ModuleType) else importlib.import_module(cand)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    <source code not available>
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    <source code not available>
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
    <source code not available>
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    <source code not available>
               ^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    <source code not available>
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    <source code not available>
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
    <source code not available>
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception (No module named 'tzdata'), another exception occurred:
  File "/lsiopy/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/healthchecks/hc/front/views.py", line 881, in details
    "downtimes": check.downtimes(3, request.profile.tz),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/healthchecks/hc/api/models.py", line 535, in downtimes
    boundaries = month_boundaries(months, tz)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/healthchecks/hc/lib/date.py", line 84, in month_boundaries
    tz = ZoneInfo(tzstr)
         ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: ZoneInfoNotFoundError at /checks/15dd4974-8752-4205-8da0-4b28abab4ff7/details/
Exception Value: 'No time zone found with key UTC+1'
```
</details>

Thanks in advance!

Edit:

🚩 [The issue ](https://github.com/linuxserver/docker-healthchecks/issues/108)in `linuxserver/docker-healthchecks` repo has been opened as well.

**Comment by cuu508** [comment]
Thanks for the report. 

Can you create a new check, and reproduce the same error with it? If yes, what are the reproduction steps? Specifically, how do you specify "UTC+1" as the timezone?

**Comment by cuu508** [comment]
Ah, OK, that explains it! Glad to hear you figured it out.

I'm not planning to add timezone validation in Django admin – there are many, many ways you can break the site from Django admin, and I don't think it makes sense to handle them all. It's a under-the-hood, you-need-to-know-what-you-are-doing type of a thing.

BTW you can also change your profile's timezone in the Account Settings / Email Reports page.
