### ISSUE TITLE
Inviting a Team Member throws exception if Django username is an email address

### ISSUE THREAD

**Issue by haikosaw** [healthchecks/healthchecks#882]
Firtly, this is a great idea & product.
Current issue:
When inviting a team member I get a Server error (500), and the log snippet below from the Docker console.
This happens when the Django username contains either of these characters: [**@**/[space]/**.**].
Django supports these characters and more [150 characters or fewer. Letters, digits and @/./+/-/_ only.], but it seems a particular function used here does not.

Why I'm seeing this problem is because I integrated the django-auth-ldap backend and as default it creates users resembling this template: user@domain.com

**To reproduce:** Just create a user with a username containing either a **space**, **period** or **@**, and invite it to a project.
**Note:** The Team member is added to the project even after this exception, just press the back button and refresh the page.

Log example with username as test.user:
```
docker-web-1  | Internal Server Error: /projects/f1069c00-f41e-4096-a6fe-3d4772d63256/settings/
docker-web-1  | Traceback (most recent call last):
docker-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
docker-web-1  |     response = get_response(request)
docker-web-1  |                ^^^^^^^^^^^^^^^^^^^^^
docker-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
docker-web-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
docker-web-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
docker-web-1  |     return view_func(request, *args, **kwargs)
docker-web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-web-1  |   File "/opt/healthchecks/hc/accounts/views.py", line 417, in project
docker-web-1  |     if project.invite(user, role=form.cleaned_data["role"]):
docker-web-1  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-web-1  |   File "/opt/healthchecks/hc/accounts/models.py", line 401, in invite
docker-web-1  |     user.profile.send_instant_login_link(membership=m, redirect_url=checks_url)
docker-web-1  |   File "/opt/healthchecks/hc/accounts/models.py", line 131, in send_instant_login_link
docker-web-1  |     path = reverse("hc-check-token", args=[self.user.username, token])
docker-web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
docker-web-1  |     return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
docker-web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
docker-web-1  |     raise NoReverseMatch(msg)
docker-web-1  | django.urls.exceptions.NoReverseMatch: Reverse for 'hc-check-token' with arguments '('test.user', 'cjBUd0GvM874VzhO6ZleNvvtxIWCD0pQ:1qY3Ok:e2bIU0mRrR8C7BkGF0_zL5yH7FNrqa9FoEANU4gYoL0')' not found. 1 pattern(s) tried: ['accounts/check_token/(?P<username>[-a-zA-Z0-9_]+)/(?P<token>[^/]+)/\\Z']
docker-web-1  | [pid: 13|app: 0|req: 136/558] 192.168.192.1 () {58 vars in 1393 bytes} [Mon Aug 21 11:48:40 2023] POST /projects/f1069c00-f41e-4096-a6fe-3d4772d63256/settings/ => generated 145 bytes in 2975 msecs (HTTP/1.1 500) 7 headers in 240 bytes (2 switches on core 0)
```

**Comment by cuu508** [comment]
Thanks for the report, @haikosaw. Fixed!
