### ISSUE TITLE
Internal server error for the docs page

### ISSUE THREAD

**Issue by hugosxm** [healthchecks/healthchecks#895]
Hi,

when I clic on the docs page I get internal server error 500, just next to "account"

Here is the log from the docker : 

```
hcio_dashboard.1.glfdb81eqgo0@healthchecks    | Internal Server Error: /docs/
hcio_dashboard.1.glfdb81eqgo0@healthchecks    | Traceback (most recent call last):
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |     response = get_response(request)
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |                ^^^^^^^^^^^^^^^^^^^^^
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |   File "/opt/healthchecks/hc/front/views.py", line 433, in serve_doc
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |     content = _replace_placeholders(doc, content)
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |   File "/opt/healthchecks/hc/front/views.py", line 405, in _replace_placeholders
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |     "SITE_HOSTNAME": site_hostname(),
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |                      ^^^^^^^^^^^^^^^
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |   File "/opt/healthchecks/hc/front/templatetags/hc_extras.py", line 70, in site_hostname
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |     return parts[1]
hcio_dashboard.1.glfdb81eqgo0@healthchecks    |            ~~~~~^^^
hcio_dashboard.1.glfdb81eqgo0@healthchecks    | IndexError: list index out of range
```

I use the SITE_NAME env and tried to add a SITE_HOSTNAME env but same result.

This is not a bad bug as the product is still perfeclty usable.

I use the v2.10 official docker image. Also I have haproxy in front but I do not think this is the problem.

**Comment by cuu508** [comment]
How does your `SITE_ROOT` setting look like, does it include scheme? i.e., is it something like `https://example.com` as opposed to `example.com`?

**Comment by hugosxm** [comment]
It fixed the problem.... sorry for that ! Thanks !

**Comment by cuu508** [comment]
Happy to hear that! So was the problem indeed a missing `http://` or `https://` prefix in  the `SITE_ROOT` value.

**Comment by hugosxm** [comment]
Yes it was missing the scheme I added `https://` in front of it

**Comment by cuu508** [comment]
We could check for this in a [System check](https://docs.djangoproject.com/en/4.2/topics/checks/) and refuse to start up if `SITE_ROOT` does not have the expected format.

I'll reopen this and close once implemented (or it turns out not to be a good idea after all).
