### ISSUE TITLE
Bit of help installing HealthChecks self hosted

### ISSUE THREAD

**Issue by JasmeowTheCat** [healthchecks/healthchecks#909]
Hello!

I have managed to get Python3.9 finally configured and installed after a bit of faff with it using Python3.8 and zoneinfo only coming into use in python3.9. so I had to use a completely different virtual thing with .venv instead of hc-env but that's all dealt with now.

I am now running into an issue where it fails due to the following:

```(.venv) root@auto:~/mychecks/healthchecks# ./manage.py migrate
Admin Command Error: ./manage.py migrate
Traceback (most recent call last):
  File "/root/mychecks/healthchecks/./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/root/mychecks/healthchecks/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/mychecks/healthchecks/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/root/mychecks/healthchecks/.venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/mychecks/healthchecks/.venv/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/root/mychecks/healthchecks/.venv/lib/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/mychecks/healthchecks/hc/api/models.py", line 29, in <module>
    from hc.api import transports
  File "/root/mychecks/healthchecks/hc/api/transports.py", line 26, in <module>
    from hc.lib import curl, emails
  File "/root/mychecks/healthchecks/hc/lib/curl.py", line 15, in <module>
    from hc.lib.typealias import JSONValue
  File "/root/mychecks/healthchecks/hc/lib/typealias.py", line 14, in <module>
    JSONValue = JSONDict | JSONList | str | int | float | bool | None
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'
Traceback (most recent call last):
  File "/root/mychecks/healthchecks/./manage.py", line 17, in <module>
    raise e
  File "/root/mychecks/healthchecks/./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/root/mychecks/healthchecks/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/mychecks/healthchecks/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/root/mychecks/healthchecks/.venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/mychecks/healthchecks/.venv/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/root/mychecks/healthchecks/.venv/lib/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/mychecks/healthchecks/hc/api/models.py", line 29, in <module>
    from hc.api import transports
  File "/root/mychecks/healthchecks/hc/api/transports.py", line 26, in <module>
    from hc.lib import curl, emails
  File "/root/mychecks/healthchecks/hc/lib/curl.py", line 15, in <module>
    from hc.lib.typealias import JSONValue
  File "/root/mychecks/healthchecks/hc/lib/typealias.py", line 14, in <module>
    JSONValue = JSONDict | JSONList | str | int | float | bool | None
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'
(.venv) root@auto:~/mychecks/healthchecks#
```

Which I don't understand why it is failing. All the requirements are good:

```(.venv) root@auto:~/mychecks/healthchecks# pip install -r requirements.txt
Requirement already satisfied: aiosmtpd==1.4.4.post2 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.4.4.post2)
Requirement already satisfied: cronsim==2.5 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.5)
Requirement already satisfied: Django==4.2.6 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (4.2.6)
Requirement already satisfied: django-compressor==4.4 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.4)
Requirement already satisfied: django-stubs-ext==4.2.2 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (4.2.2)
Requirement already satisfied: fido2==1.1.2 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.1.2)
Requirement already satisfied: psycopg2==2.9.9 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (2.9.9)
Requirement already satisfied: pycurl==7.45.2 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (7.45.2)
Requirement already satisfied: pydantic==2.4.2 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (2.4.2)
Requirement already satisfied: pyotp==2.9.0 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (2.9.0)
Requirement already satisfied: segno==1.5.2 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (1.5.2)
Requirement already satisfied: statsd==4.0.1 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (4.0.1)
Requirement already satisfied: whitenoise==6.5.0 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 13)) (6.5.0)
Requirement already satisfied: attrs in ./.venv/lib/python3.9/site-packages (from aiosmtpd==1.4.4.post2->-r requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: atpublic in ./.venv/lib/python3.9/site-packages (from aiosmtpd==1.4.4.post2->-r requirements.txt (line 1)) (4.0)
Requirement already satisfied: sqlparse>=0.3.1 in ./.venv/lib/python3.9/site-packages (from Django==4.2.6->-r requirements.txt (line 3)) (0.4.4)
Requirement already satisfied: asgiref<4,>=3.6.0 in ./.venv/lib/python3.9/site-packages (from Django==4.2.6->-r requirements.txt (line 3)) (3.7.2)
Requirement already satisfied: rcssmin==1.1.1 in ./.venv/lib/python3.9/site-packages (from django-compressor==4.4->-r requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: rjsmin==1.2.1 in ./.venv/lib/python3.9/site-packages (from django-compressor==4.4->-r requirements.txt (line 4)) (1.2.1)
Requirement already satisfied: django-appconf>=1.0.3 in ./.venv/lib/python3.9/site-packages (from django-compressor==4.4->-r requirements.txt (line 4)) (1.0.5)
Requirement already satisfied: typing-extensions in ./.venv/lib/python3.9/site-packages (from django-stubs-ext==4.2.2->-r requirements.txt (line 5)) (4.8.0)
Requirement already satisfied: cryptography!=35,<44,>=2.6 in ./.venv/lib/python3.9/site-packages (from fido2==1.1.2->-r requirements.txt (line 6)) (41.0.4)
Requirement already satisfied: pydantic-core==2.10.1 in ./.venv/lib/python3.9/site-packages (from pydantic==2.4.2->-r requirements.txt (line 9)) (2.10.1)
Requirement already satisfied: annotated-types>=0.4.0 in ./.venv/lib/python3.9/site-packages (from pydantic==2.4.2->-r requirements.txt (line 9)) (0.6.0)
Requirement already satisfied: cffi>=1.12 in ./.venv/lib/python3.9/site-packages (from cryptography!=35,<44,>=2.6->fido2==1.1.2->-r requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: pycparser in ./.venv/lib/python3.9/site-packages (from cffi>=1.12->cryptography!=35,<44,>=2.6->fido2==1.1.2->-r requirements.txt (line 6)) (2.21)
(.venv) root@auto:~/mychecks/healthchecks#
```

Not sure where to go from here. Any help would be fantastic.

**Comment by cuu508** [comment]
Hey @JasmeowTheCat, 

Starting from version 3.0, Healthchecks requires Python 3.10 or later. The error is about Python 3.9 not recognizing type hint syntax that indeed was not yet supported in 3.9. 

If you must use Python 3.9, you could look at using Healthchecks 2.10 which should work.

**Comment by JasmeowTheCat** [comment]
Hey Cuu508,

Thanks for that, solved that now by using a docker container, but now I am running into a issue similar to this:

https://github.com/linuxserver/docker-healthchecks/issues/67

Where I am getting the below error:

```
healthchecks  | [WARNING] unable to add HTTP_COOKIE=rl_page_init_referrer=RudderEncrypt%3AU2FsdGVkX1%2B0HOZHv4XenvlvIeddmKB8A4J6MHrjS0Q%3D; rl_page_init_referring_domain=RudderEncrypt%3AU2FsdGVkX186S2vLuccSFAWAXr46s2RLYRYyQtOJk38%3D; _ga=GA1.1.251161173.1688162513; csrftoken=YsvdnkEIpd1wQJBN5fk2yvulMf6S4ejb; sessionid=3moquc22zd6brlts2pqvw6167c4h46di; _ga_CPRJXK1RJ1=GS1.1.1697652502.11.1.1697653155.0.0.0; _ga_7RPPWFB092=GS1.1.1697653201.1.1.1697653396.0.0.0; rl_anonymous_id=RudderEncrypt%3AU2FsdGVkX1%2FAARDlmyQtOipjlbccZg27DIvwZuR0f5I1FBh4T3qTXA7%2FJpfzVoe7Jf7%2B%2FkMPZMFM9XNoemGsgw%3D%3D; rl_group_id=RudderEncrypt%3AU2FsdGVkX187cjGRT%2FYUz1Wz%2BoGsmjvX4cY%2FdgO%2FDVE%3D; rl_group_trait=RudderEncrypt%3AU2FsdGVkX1%2BSzGFMt56KwcIawJ0aA5Nx%2BPO%2Fyry3RgE%3D; rl_user_id=RudderEncrypt%3AU2FsdGVkX1%2Bc3bPGOj5FCoW1JzWTZbOC6ETI05MBdLqIB5bVjb2Xat03RLA6%2FxU4BUiS7RhhAGgYKllkCQgYjQrka%2FQhdJeXZjlfvsENRUiwfkPrXkzSK1AffQPZt3TTSapOuPELLv48OEzbJtsKntjnWovneY5fPg6h9H9HfDE%3D; rl_trait=RudderEncrypt%3AU2FsdGVkX1%2FTOFOMlk4vDbRrpnitD%2FByXIkJ%2FhSJDua2iUi8LOIjcFBMxSrGLyuaZq0AoscudOsVPSwK0nxfUOH%2FKCBqGorw4FUK8f1BUnSBUYT0ws2P9NC8qBnDRDb1Wg%2BGqA5iB0Mz0NSOlteXMGOoSx2TU%2FBrIFWFa671%2Fn4%3D; ph_phc_4URIAm1uYfJO7j8kWSe0J8lc8IqnstRLS7Jx8NcakHo_posthog=%7B%22%24active_feature_flags%22%3A%5B%22014_demo_onboarding%22%2C%22011_ask_AI%22%2C%22009_choosing_trial_plan%22%2C%22006_cloud_opt_in%22%2C%22schema-view%22%5D%2C%22%24enabled_feature_flags%22%3A%7B%22014_demo_onboarding%22%3A%22variant%22%2C%22011_ask_AI%22%3A%22gpt3%22%2C%22009_choosing_trial_plan%22%3A%22variant%22%2C%22006_cloud_opt_in%22%3A%22control%22%2C%22schema-view%22%3Atrue%7D%2C%22%24feature_flag_payloads%22%3A%7B%7D%2C%22distinct_id%22%3A%2258eea6d43836b4dd227520207ef14c541a67cca35c0c04e7b50b0c26b8fa7fc8%231643899f-03cf-4835-8b08-937d88e4a50e%22%2C%22%24device_id%22%3A%22018b4403-eee1-773a-8584-1e8cffb9891b%22%2C%22%24user_state%22%3A%22identified%22%2C%22%24user_id%22%3A%2258eea6d43836b4dd227520207ef14c541a67cca35c0c04e7b50b0c26b8fa7fc8%231643899f-03cf-4835-8b08-937d88e4a50e%22%2C%22%24stored_person_properties%22%3A%7B%22instance_id%22%3A%2258eea6d43836b4dd227520207ef14c541a67cca35c0c04e7b50b0c26b8fa7fc8%22%2C%22created_at_timestamp%22%3A1697646236362%7D%2C%22%24sesid%22%3A%5B1697654077825%2C%22018b4403-eee3-7b01-b2d1-b3e9b581fcba%22%2C1697653190371%5D%2C%22%24session_recording_enabled_server_side%22%3Afalse%2C%22%24autocapture_disabled_server_side%22%3Afalse%7D; rl_session=RudderEncrypt%3AU2FsdGVkX18%2Fz0o%2BNZXy7X1wFRafeXD1YKK2naBONjBUZ5iUOYMG644Dk8%2BzBhYFS5qwqIPG7XMadGjyVKViUu3wtjJdx5FtwQggktmky6bQoi6%2Ft%2FNcmxob%2BYaeeg1pqwQgIfLEK1WE%2Bw1VXM%2BB6w%3D%3D to uwsgi packet, consider increasing buffer size```

**Comment by JasmeowTheCat** [comment]
Solved it:

After further reading of the docker compose file examples, I read you used - UWSGI_ as a env parameter, so I then put BUFFER_SIZE from their documentation.

- UWSGI_BUFFER_SIZE=32768

Now works fine.
